### PR TITLE
Fix Broken Link in README

### PR DESCRIPTION
**Pull request by CharleyPeng1**
Using relative links is simpler to maintain.

### CODE REVIEW

**Comment by dylanninin** [comment]
Well, the "continue reading" link is broken

**Comment by CharleyPeng1** [comment]
It works with this commit when I tested it.

https://github.com/CharleyPeng1/security-101-for-saas-startups/blob/f68fa151e2ca610fd118f34ddeb98af484f74b6a/readme.md

**Comment by MACLIPSTICK** [comment]
What am I tinlook for this person I've seen before Itzel this man from Russia? Is he helping my husband with blocking my phone or is it a hack to him and i and or both since he's so dumb to trust anyone over the internet 

Blessings,
Mrs. Gigi DiBernardo 🌺

**Comment by itaifrenkel** [comment]
We need the absolute link when embedding the readme.md in other sites. The abs link was fixed

**Comment by CharleyPeng1** [comment]
I think the image links are broken

**Pull request closed without merging**
