### PR TITLE
Translate to chinese PR #54

### PR DESCRIPTION
**Pull request by b051**

### CODE REVIEW

**Comment by itaifrenkel** [comment]
@b051 Could you please check my last commit? see https://github.com/forter/security-101-for-saas-startups/pull/54/files

**Comment by itaifrenkel** [comment]
@b051 I think you might need to merge this branch with upstream/chinese since it looks like the link to the english translation is already in upstream/chinese.

**Comment by b051** [comment]
updated to
    * 除此之外，你还需要执行[渗透测试](#防止你的对外互联网服务的被黑)。

**Comment by itaifrenkel** [comment]
thanks @b051 :)

**Pull request merged**
